import type { SubmissionDetail, OpponentResult } from "../api/client";

export function exportPdf(submission: SubmissionDetail) {
  const results = submission.results;
  const role = submission.role;

  let avgHtml = "";
  if (results) {
    const accs = Object.entries(results)
      .filter(([k]) => k !== "__summary__")
      .map(([, r]) => r.avg_final_accuracy)
      .filter((a): a is number => a != null);
    const avg = accs.length ? accs.reduce((a, b) => a + b, 0) / accs.length : null;
    if (avg != null) {
      const note = role === "attack" ? "lower = stronger" : "higher = stronger";
      avgHtml = `<div class="summary-box"><strong>Overall Average Accuracy:</strong> ${avg.toFixed(4)} <span class="note">(${note})</span></div>`;
    }
  }

  const resultsTable = results ? buildResultsTable(results) : "";
  const codeHtml = escapeHtml(submission.code);

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Report: ${escapeHtml(submission.display_name)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1e293b; line-height: 1.6; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 1.5rem; }
  .meta span { margin-right: 1.5rem; }
  .mono { font-family: "SF Mono", "Fira Code", monospace; }
  .description { color: #475569; margin-bottom: 1.5rem; }
  .summary-box { background: #f1f5f9; border-radius: 8px; padding: 12px 16px; margin-bottom: 1.5rem; }
  .note { color: #64748b; font-size: 0.8rem; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; font-size: 0.875rem; }
  th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #e2e8f0; color: #64748b; font-weight: 600; }
  td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  td.num { text-align: right; font-family: "SF Mono", monospace; }
  pre { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; overflow-x: auto; font-size: 0.8rem; line-height: 1.5; }
  code { font-family: "SF Mono", "Fira Code", monospace; }
  .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.75rem; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>${escapeHtml(submission.display_name)}</h1>
  <div class="meta">
    <span class="mono">${escapeHtml(submission.method_name)}</span>
    <span>Role: ${role}</span>
    ${submission.author ? `<span>Author: ${escapeHtml(submission.author)}</span>` : ""}
    <span>Status: ${submission.status}</span>
  </div>
  ${submission.description ? `<p class="description">${escapeHtml(submission.description)}</p>` : ""}
  ${avgHtml}
  ${resultsTable}
  <h2>Code</h2>
  <pre><code>${codeHtml}</code></pre>
  <div class="footer">Generated by FedArena</div>
  <script>window.onload = () => setTimeout(() => window.print(), 300);</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

function buildResultsTable(results: Record<string, OpponentResult>): string {
  const entries = Object.entries(results).filter(([k]) => k !== "__summary__");
  if (entries.length === 0) return "";

  const header = "<th>Opponent</th><th style='text-align:right'>Accuracy</th><th style='text-align:right'>Acc. Drop</th><th style='text-align:right'>Convergence</th><th style='text-align:right'>Stability</th>";

  let rows = "";
  for (const [opp, res] of entries) {
    const label = opp.replace("__none__", "none").replace("baseline_", "");
    const acc = res.avg_final_accuracy != null ? res.avg_final_accuracy.toFixed(4) : "FAIL";
    const drop = res.accuracy_drop != null ? res.accuracy_drop.toFixed(4) : "-";
    const conv = res.avg_convergence_speed != null ? `${Math.round(res.avg_convergence_speed)}` : "-";
    const stab = res.avg_stability != null ? res.avg_stability.toFixed(4) : "-";
    rows += `<tr><td class="mono">${escapeHtml(label)}</td><td class="num">${acc}</td><td class="num">${drop}</td><td class="num">${conv}</td><td class="num">${stab}</td></tr>`;
  }

  return `<h2>Results</h2><table><thead><tr>${header}</tr></thead><tbody>${rows}</tbody></table>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
