"""Generate Markdown evaluation reports for submissions."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def generate_markdown_report(
    submission: dict[str, Any],
    results: dict[str, Any] | None,
) -> str:
    role = submission["role"]
    lines: list[str] = []

    lines.append(f"# Evaluation Report: {submission['display_name']}")
    lines.append("")
    lines.append(f"- **Method:** `{submission['method_name']}`")
    lines.append(f"- **Role:** {role}")
    if submission.get("author"):
        lines.append(f"- **Author:** {submission['author']}")
    lines.append(f"- **Status:** {submission['status']}")
    lines.append(f"- **Submitted:** {_fmt_dt(submission['created_at'])}")
    lines.append("")

    if submission.get("description"):
        lines.append("## Description")
        lines.append("")
        lines.append(submission["description"])
        lines.append("")

    if results:
        if "scenarios" in results:
            for sc_id, sc_results in results["scenarios"].items():
                lines.append(f"## Scenario: {sc_id}")
                lines.append("")
                _append_results(lines, sc_results, role)
        else:
            _append_results(lines, results, role)

    lines.append("## Code")
    lines.append("")
    lines.append("```python")
    lines.append(submission["code"])
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by FedArena*")
    lines.append("")

    return "\n".join(lines)


def _append_results(
    lines: list[str],
    results: dict[str, Any],
    role: str,
) -> None:
    summary = results.get("__summary__", {})
    opponent_results = {k: v for k, v in results.items() if k != "__summary__"}

    accs = [r["avg_final_accuracy"] for r in opponent_results.values() if r.get("avg_final_accuracy") is not None]
    avg = sum(accs) / len(accs) if accs else None

    lines.append("## Summary")
    lines.append("")
    if avg is not None:
        lines.append(f"- **Overall Average Accuracy:** {avg:.4f}")
    if summary.get("avg_accuracy_drop") is not None:
        lines.append(f"- **Average Accuracy Drop:** {summary['avg_accuracy_drop']:.4f}")
    if summary.get("worst_case_accuracy") is not None:
        lines.append(f"- **Worst-Case Accuracy:** {summary['worst_case_accuracy']:.4f}")
    if summary.get("avg_convergence_speed") is not None:
        lines.append(f"- **Average Convergence Speed:** {summary['avg_convergence_speed']:.1f} rounds")
    if summary.get("avg_stability") is not None:
        lines.append(f"- **Average Stability (std):** {summary['avg_stability']:.4f}")
    if summary.get("avg_runtime_seconds") is not None:
        lines.append(f"- **Average Runtime:** {summary['avg_runtime_seconds']:.1f}s")
    lines.append(f"- **Opponents Evaluated:** {len(opponent_results)}")
    interpretation = "lower = stronger attack" if role == "attack" else "higher = stronger defense"
    lines.append(f"- **Interpretation:** {interpretation}")
    lines.append("")

    lines.append("## Per-Opponent Results")
    lines.append("")
    lines.append("| Opponent | Accuracy | Acc. Drop | Convergence | Stability |")
    lines.append("|----------|----------|-----------|-------------|-----------|")

    for opp, res in opponent_results.items():
        opp_label = opp.replace("__none__", "none").replace("baseline_", "")
        acc_str = f"{res['avg_final_accuracy']:.4f}" if res.get("avg_final_accuracy") is not None else "FAIL"
        drop_str = f"{res['accuracy_drop']:.4f}" if res.get("accuracy_drop") is not None else "-"
        conv_str = f"{res['avg_convergence_speed']:.0f}" if res.get("avg_convergence_speed") is not None else "-"
        stab_str = f"{res['avg_stability']:.4f}" if res.get("avg_stability") is not None else "-"
        lines.append(f"| {opp_label} | {acc_str} | {drop_str} | {conv_str} | {stab_str} |")

    lines.append("")

    _append_trajectories(lines, opponent_results)


def _append_trajectories(
    lines: list[str],
    results: dict[str, Any],
) -> None:
    has_trajectory = any(
        any(s.get("accuracy_trajectory") and len(s["accuracy_trajectory"]) > 0 for s in r.get("per_seed", []))
        for r in results.values()
    )
    if not has_trajectory:
        return

    lines.append("## Training Trajectories")
    lines.append("")

    for opp, res in results.items():
        opp_label = opp.replace("__none__", "none").replace("baseline_", "")
        seeds = res.get("per_seed", [])
        seed_with_data = [s for s in seeds if s.get("accuracy_trajectory")]
        if not seed_with_data:
            continue

        lines.append(f"### vs {opp_label}")
        lines.append("")

        ref = seed_with_data[0]
        rounds = ref.get("rounds", list(range(1, len(ref["accuracy_trajectory"]) + 1)))

        header = "| Round |" + " | ".join(f"Seed {s['seed']} Acc" for s in seed_with_data) + " |"
        separator = "|-------|" + " | ".join("--------" for _ in seed_with_data) + " |"
        lines.append(header)
        lines.append(separator)

        for i, rnd in enumerate(rounds):
            row = f"| {rnd} |"
            for s in seed_with_data:
                traj = s["accuracy_trajectory"]
                val = f" {traj[i]:.4f} |" if i < len(traj) and traj[i] is not None else " - |"
                row += val
            lines.append(row)

        lines.append("")


def _fmt_dt(val: Any) -> str:
    if isinstance(val, datetime):
        return val.strftime("%Y-%m-%d %H:%M UTC")
    if isinstance(val, str):
        try:
            dt = datetime.fromisoformat(val)
            return dt.strftime("%Y-%m-%d %H:%M UTC")
        except ValueError:
            return val
    return str(val)
