"""Generate Markdown evaluation reports for submissions."""

from __future__ import annotations

from datetime import datetime
from typing import Any


def generate_markdown_report(
    submission: dict[str, Any],
    results: dict[str, Any] | None,
) -> str:
    role = submission["role"]
    lines: list[str] = []

    lines.append(f"# Evaluation Report: {submission['display_name']}")
    lines.append("")
    lines.append(f"- **Method:** `{submission['method_name']}`")
    lines.append(f"- **Role:** {role}")
    if submission.get("author"):
        lines.append(f"- **Author:** {submission['author']}")
    lines.append(f"- **Status:** {submission['status']}")
    lines.append(f"- **Submitted:** {_fmt_dt(submission['created_at'])}")
    lines.append("")

    if submission.get("description"):
        lines.append("## Description")
        lines.append("")
        lines.append(submission["description"])
        lines.append("")

    if results:
        _append_results(lines, results, role)

    lines.append("## Code")
    lines.append("")
    lines.append("```python")
    lines.append(submission["code"])
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by FedArena*")
    lines.append("")

    return "\n".join(lines)


def _append_results(
    lines: list[str],
    results: dict[str, Any],
    role: str,
) -> None:
    accs = [r["avg_final_accuracy"] for r in results.values() if r.get("avg_final_accuracy") is not None]
    avg = sum(accs) / len(accs) if accs else None

    lines.append("## Summary")
    lines.append("")
    if avg is not None:
        lines.append(f"- **Overall Average Accuracy:** {avg:.4f}")
    lines.append(f"- **Opponents Evaluated:** {len(results)}")
    interpretation = "lower = stronger attack" if role == "attack" else "higher = stronger defense"
    lines.append(f"- **Interpretation:** {interpretation}")
    lines.append("")

    multi_seed = any(len(r.get("per_seed", [])) > 1 for r in results.values())

    lines.append("## Per-Opponent Results")
    lines.append("")

    if multi_seed:
        lines.append("| Opponent | Avg Accuracy | Per Seed |")
        lines.append("|----------|-------------|----------|")
    else:
        lines.append("| Opponent | Accuracy |")
        lines.append("|----------|----------|")

    for opp, res in results.items():
        opp_label = opp.replace("__none__", "none").replace("baseline_", "")
        acc_str = f"{res['avg_final_accuracy']:.4f}" if res.get("avg_final_accuracy") is not None else "FAIL"
        if multi_seed:
            seeds_str = ", ".join(
                f"{s['final_accuracy']:.4f}" if s.get("final_accuracy") is not None else "fail"
                for s in res.get("per_seed", [])
            )
            lines.append(f"| {opp_label} | {acc_str} | {seeds_str} |")
        else:
            lines.append(f"| {opp_label} | {acc_str} |")

    lines.append("")

    _append_trajectories(lines, results)


def _append_trajectories(
    lines: list[str],
    results: dict[str, Any],
) -> None:
    has_trajectory = any(
        any(s.get("accuracy_trajectory") and len(s["accuracy_trajectory"]) > 0 for s in r.get("per_seed", []))
        for r in results.values()
    )
    if not has_trajectory:
        return

    lines.append("## Training Trajectories")
    lines.append("")

    for opp, res in results.items():
        opp_label = opp.replace("__none__", "none").replace("baseline_", "")
        seeds = res.get("per_seed", [])
        seed_with_data = [s for s in seeds if s.get("accuracy_trajectory")]
        if not seed_with_data:
            continue

        lines.append(f"### vs {opp_label}")
        lines.append("")

        ref = seed_with_data[0]
        rounds = ref.get("rounds", list(range(1, len(ref["accuracy_trajectory"]) + 1)))

        header = "| Round |" + " | ".join(f"Seed {s['seed']} Acc" for s in seed_with_data) + " |"
        separator = "|-------|" + " | ".join("--------" for _ in seed_with_data) + " |"
        lines.append(header)
        lines.append(separator)

        for i, rnd in enumerate(rounds):
            row = f"| {rnd} |"
            for s in seed_with_data:
                traj = s["accuracy_trajectory"]
                val = f" {traj[i]:.4f} |" if i < len(traj) and traj[i] is not None else " - |"
                row += val
            lines.append(row)

        lines.append("")


def _fmt_dt(val: Any) -> str:
    if isinstance(val, datetime):
        return val.strftime("%Y-%m-%d %H:%M UTC")
    if isinstance(val, str):
        try:
            dt = datetime.fromisoformat(val)
            return dt.strftime("%Y-%m-%d %H:%M UTC")
        except ValueError:
            return val
    return str(val)
